### ISSUE TITLE
Allow x.y.* syntax

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/composer-prefer-lowest#7]
```
Fatal error: Uncaught UnexpectedValueException: Invalid version string "3.5.*" in /home/travis/build/cakephp/cakephp-codesniffer/vendor/composer/semver/src/VersionParser.php:172
Stack trace:
#0 /home/travis/build/cakephp/cakephp-codesniffer/vendor/dereuromark/composer-prefer-lowest/src/Validator.php(182): Composer\Semver\VersionParser->normalize('3.5.*')
#1 /home/travis/build/cakephp/cakephp-codesniffer/vendor/dereuromark/composer-prefer-lowest/src/Validator.php(57): ComposerPreferLowest\Validator->normalizeVersion('3.5.*')
```

**Comment by dereuromark** [comment]
Closed in https://github.com/dereuromark/composer-prefer-lowest/commit/45aeb9b787b3d3984dc86778e31f732e1270a930
