### ISSUE TITLE
Cannot use version ranges

### ISSUE THREAD

**Issue by othercorey** [dereuromark/composer-prefer-lowest#8]
We are hitting this error in cakephp-codesniffer with this version constraint:

> "slevomat/coding-standard": ">=6.0 <6.2"

https://travis-ci.com/github/cakephp/cakephp-codesniffer/jobs/319510577

```
Fatal error: Uncaught UnexpectedValueException: Invalid version string "6.0 <6.2" in /home/travis/build/cakephp/cakephp-codesniffer/vendor/composer/semver/src/VersionParser.php:176
Stack trace:
#0 /home/travis/build/cakephp/cakephp-codesniffer/vendor/dereuromark/composer-prefer-lowest/src/Validator.php(205): Composer\Semver\VersionParser->normalize('6.0 <6.2')
#1 /home/travis/build/cakephp/cakephp-codesniffer/vendor/dereuromark/composer-prefer-lowest/src/Validator.php(111): ComposerPreferLowest\Validator->normalizeVersion('6.0 <6.2')
#2 /home/travis/build/cakephp/cakephp-codesniffer/vendor/dereuromark/composer-prefer-lowest/src/Validator.php(62): ComposerPreferLowest\Validator->definedMinimum(Array, 'slevomat/coding...')
#3 /home/travis/build/cakephp/cakephp-codesniffer/vendor/dereuromark/composer-prefer-lowest/src/Validator.php(42): ComposerPreferLowest\Validator->compare('/home/travis/bu...', '/home/travis/bu...', Array)
#4 /home/travis/build/cakephp/cakephp-codesniffer/vendor/dereuromark/composer-prefer-lowest/bin/vali in /home/travis/build/cakephp/cakephp-codesniffer/vendor/composer/semver/src/VersionParser.php on line 176
```

**Comment by dereuromark** [comment]
Thx, I can either look into it and fix this, or we ignore these kind of ranges.

**Comment by dereuromark** [comment]
Composer sure has a handy method to parse ranges and give us the min, right?

EDIT, AH: https://github.com/composer/semver/blob/master/src/VersionParser.php#L229

**Comment by dereuromark** [comment]
Should be fixed with https://github.com/dereuromark/composer-prefer-lowest/commit/37fc7aeb2abc88854a07c76632378269a122a0af

**Comment by dereuromark** [comment]
Jep, all green.
